---
title: "Problem_1"
author: "Shengnan Sun"
date: "2017-10-23"
output: html_document
---

```{r plot_format}
#embedding plots in rmarkdown
knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 1,
  out.width = "120%"
)
```

```{r load packages}
library(knitr)
library(tidyverse)
library(ggridges)
library(ggthemes)
library(haven)
library(readxl)
library(janitor)
```

## Problem 1

```{r tidy_data}
pup_data = read_csv("FAS_pups.csv", col_types = "ciiiii") %>% # load data
  clean_names() %>% # clean column names
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) %>% # recode sex as male and female
  gather(key = landmarks, value = PD_outcome, pd_ears:pd_walk) %>% # reshape from wide to long 
  filter(!is.na(PD_outcome)) # remove the rows where PD_outcome is NA
```

```{r make a plot}
ggplot(pup_data, aes(x = PD_outcome, y = landmarks)) + 
  geom_density_ridges(scale = .85) +
  labs(title = "Distribution of post-natal days/landmark",
    x = "PD_outcome",
    y = "landmarks") + 
    theme(text = element_text(size = 15))
```

The ridge plot above shows the distribution of post-natal days for the landmarks of "pd_ears", "pd_eyes", "pd_pivot" and "pd_walk". In general, "Pd_ears" develop earlier than other landmarks, "pd_eyes" develop much later. The development period for "pd_pivot" and "pd_walk" have a significant overlapping.